### ISSUE TITLE
S4 - AutoFit

### ISSUE THREAD

**Issue by baltazaroliveira** [grantland/android-autofittextview#22]
I´m creating a list view with a lot of fields and with S4 the fiels don´t make the autofit. I think that the problem is the little space available.

In S4

![image](https://cloud.githubusercontent.com/assets/953742/4574000/54588dac-4f98-11e4-8097-3c7fdf208dfc.png)

What should appear

![image](https://cloud.githubusercontent.com/assets/953742/4574016/8906a25a-4f98-11e4-8bd2-51182c4af48f.png)

The code
```
<me.grantland.widget.AutofitTextView
            android:id="@+id/data_entrada"
            android:layout_width="0dip"
            android:layout_height="wrap_content"
            android:layout_weight="16"

            android:singleLine="true"/> <!-- obrigatório -->
```
Do you have any quick fix?

Thanks

**Comment by pkoutsias** [comment]
I had the same problem, and I found out that the minSize of 8 would not fit. Maybe related to #23

**Comment by grantland** [comment]
Merging into #23 

Feel free to reopen if you this this was a mistake.
