### ISSUE TITLE
wrong size on Nexus 5

### ISSUE THREAD

**Issue by SimonStefan** [grantland/android-autofittextview#34]
I used AutofitTextView with xml and the text was nearly two times larger on a Nexus 5 (API21) than on Nexus 7 (2013, API21) or Nexus 4 (API15). Using "AutofitHelper.create(textView);" with a normal TextView worked. Maybe there is a problem with xxhdpi devices?

**Comment by grantland** [comment]
Would you be able to post a screenshot and details of what attributes you're using? There also was an issue where the minTextSize wasn't set properly (used px instead of sp), have you tried master?

https://github.com/grantland/android-autofittextview/issues/23

**Comment by SimonStefan** [comment]
No, I only tried the current version on Maven and have already refactored the code. To set the AutofitHelper programmatically was a really quick fix, so in my opinion you can close this issue. I just wanted it to be report, if somebody else has the same issue.
