### ISSUE TITLE
Stop auto-fitting

### ISSUE THREAD

**Issue by azurh** [grantland/android-autofittextview#51]
Is there a way to unlink a `TextView` with this library? I have to find the smallest `textSize` for a particular `TextView` and store it, and then set a very new `textSize` to that `TextView`. 
However, the `TextView's` text gets resized, no matter the new `textSize` I've set. I have also tried to reinitialize the `TextView` via the `findViewById` method.

I am using regular `TextView` in my xml, and then `AutoFitHelper.create(myTextView)` in code.

There must be a workaround here.

**Comment by grantland** [comment]
`AutoFitHelper.create(myTextView)` should return an instance of `AutoFitHelper` that you could toggle `setEnabled(enabled)`, have you tried this?

**Comment by azurh** [comment]
It works now. Wasn't aware of that method. Thanks!
