### ISSUE TITLE
Use lower value of minSdkVersion?

### ISSUE THREAD

**Issue by nileshtrivedi** [grantland/android-autofittextview#54]
Is it possible to use a lower value for minSdkVersion? Currently, AutofitTextView is the reason why my app is forced to use minSdkVersion=14 and it would be really great to support version 10.

**Comment by nileshtrivedi** [comment]
Possible duplicate: https://github.com/grantland/android-autofittextview/issues/33

**Comment by grantland** [comment]
Unfortunately I won't have any plans to lower the `minSdkVersion` and it seems you've already found the fork that does :smile:
