### ISSUE TITLE
Autofit for height as well as for width

### ISSUE THREAD

**Issue by ChristianKleineidam** [grantland/android-autofittextview#67]
I have data that's sometimes one line and other times two lines.
If it's one line I want the text size to double.

I used an `autofittextview` with
            android:layout_height="60dp"
            android:maxLines="2"
            android:textSize="40sp"
            autofit:minTextSize="16sp"

This causes my text to overflow. Is there a setting that prevents the overflow and instead reduces the text size?

**Comment by grantland** [comment]
Unfortunately, this seems out of the scope of this library.
